import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type {
  Project,
  ScheduleResult,
  ScheduledTask,
  ZoomLevel,
} from "../types";
import { STATUS_META } from "./factory";
import { formatShort } from "./dates";
import { drawGanttPages } from "./pdf-gantt";

/**
 * Professional NASA-style technical PDF report (jsPDF + autoTable + a native
 * vector Gantt renderer). Structure:
 *   1. Title page — project identity, revision, date, and the ONLY place the
 *      "Generated by Asrar ul Haq" branding appears.
 *   2. Document control (info + revision history + summary).
 *   3. Task schedule table.
 *   4. Native-vector Gantt chart, tiled/paginated across pages (see pdf-gantt).
 *
 * The Gantt is drawn as true vector primitives — no rasterized image — so it is
 * crisp at any print resolution and scales to hundreds of tasks via 2-D
 * pagination. Branding never appears on the Gantt/data/appendix pages.
 */

const NASA_BLUE: [number, number, number] = [11, 61, 145]; // NASA "meatball" blue
const ACCENT: [number, number, number] = [79, 70, 229];
const INK: [number, number, number] = [23, 23, 30];
const MUTED: [number, number, number] = [110, 110, 130];

export interface PdfOptions {
  paper: "a4" | "letter";
  zoom: ZoomLevel;
}

export function exportPDF(
  project: Project,
  schedule: ScheduleResult,
  opts: PdfOptions,
  filename: string,
): void {
  const doc = new jsPDF({
    unit: "mm",
    format: opts.paper,
    orientation: "portrait",
  });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 18;

  titlePage(doc, project, pageW, pageH, margin);

  doc.addPage();
  documentControlPage(doc, project, schedule, margin);

  doc.addPage();
  taskTablePage(doc, project, schedule, margin);

  // Native-vector Gantt, appended as its own landscape page(s).
  drawGanttPages(doc, project, schedule, {
    paper: opts.paper,
    zoom: opts.zoom,
    margin,
  });

  // Page numbers on every page except the title page. NO author branding here.
  paginate(doc, margin);
  doc.save(`${filename}.pdf`);
}

/** The only page carrying the "Generated by Asrar ul Haq" branding. */
function titlePage(
  doc: jsPDF,
  project: Project,
  pageW: number,
  pageH: number,
  margin: number,
) {
  const m = project.meta;

  // NASA-style top band + thin accent rule.
  doc.setFillColor(...NASA_BLUE);
  doc.rect(0, 0, pageW, 5, "F");

  const logoY = 26;
  if (m.organizationLogo)
    addImageSafe(doc, m.organizationLogo, margin, logoY, 40, 20);
  if (m.projectLogo)
    addImageSafe(
      doc,
      m.projectLogo,
      pageW - margin - 40,
      logoY,
      40,
      20,
      "right",
    );

  // Document classifier line.
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...NASA_BLUE);
  doc.text("TECHNICAL PROJECT SCHEDULE", margin, pageH * 0.34);

  // Title.
  const cy = pageH * 0.4;
  doc.setTextColor(...INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(30);
  const titleLines = doc.splitTextToSize(
    m.name || "Project Plan",
    pageW - margin * 2,
  );
  doc.text(titleLines, margin, cy);

  const subtitle = m.description?.split("\n")[0] ?? "";
  let afterTitle = cy + titleLines.length * 11 + 4;
  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(13);
    doc.setTextColor(...MUTED);
    const subLines = doc.splitTextToSize(subtitle, pageW - margin * 2);
    doc.text(subLines, margin, afterTitle);
    afterTitle += subLines.length * 6 + 2;
  }

  doc.setDrawColor(...ACCENT);
  doc.setLineWidth(1);
  doc.line(margin, afterTitle + 4, margin + 60, afterTitle + 4);

  // Info block.
  const infoY = pageH * 0.64;
  const info: Array<[string, string]> = [
    ["Client", m.client || "—"],
    ["Organization", m.organization || "—"],
    ["Prepared by", m.projectManager || "—"],
    ["Date", formatShort(new Date().toISOString().slice(0, 10))],
    ["Version / Revision", `${m.version || "1.0"} / ${m.revision || "A"}`],
    ["Document No.", m.documentNumber || "—"],
  ];
  doc.setFontSize(10);
  info.forEach(([label, value], i) => {
    const y = infoY + i * 7;
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...INK);
    doc.text(label, margin, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...MUTED);
    doc.text(value, margin + 44, y);
  });

  // Branding — TITLE PAGE ONLY.
  doc.setDrawColor(...NASA_BLUE);
  doc.setLineWidth(0.4);
  doc.line(margin, pageH - 22, pageW - margin, pageH - 22);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  doc.text("Generated by Asrar ul Haq", pageW / 2, pageH - 15, {
    align: "center",
  });
}

function documentControlPage(
  doc: jsPDF,
  project: Project,
  schedule: ScheduleResult,
  margin: number,
) {
  const m = project.meta;
  let y = sectionHeader(doc, "1  Document Information", margin, 24);

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: "grid",
    styles: { fontSize: 9.5, cellPadding: 2.5 },
    body: [
      ["Project", m.name],
      ["Client", m.client || "—"],
      ["Organization", m.organization || "—"],
      ["Project Manager", m.projectManager || "—"],
      ["Team", m.team || "—"],
      ["Document Number", m.documentNumber || "—"],
      [
        "Schedule Window",
        `${formatShort(m.startDate)} → ${formatShort(m.endDate)}`,
      ],
      ["Total Duration", `${schedule.stats.totalDurationDays} days`],
      ["Description", m.description || "—"],
    ],
    columnStyles: { 0: { cellWidth: 46, fontStyle: "bold", textColor: MUTED } },
  });
  y = lastY(doc, y) + 8;

  y = sectionHeader(doc, "2  Revision History", margin, y);
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: "striped",
    styles: { fontSize: 9.5, cellPadding: 2.5 },
    head: [["Rev", "Date", "Description", "Author"]],
    headStyles: { fillColor: NASA_BLUE, textColor: 255 },
    body: [
      [
        m.revision || "A",
        formatShort(new Date().toISOString().slice(0, 10)),
        "Issued for review",
        m.projectManager || "—",
      ],
    ],
  });
  y = lastY(doc, y) + 8;

  y = sectionHeader(doc, "3  Summary", margin, y);
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: "grid",
    styles: { fontSize: 9.5, cellPadding: 2.5 },
    body: [
      ["Total tasks", String(schedule.stats.totalTasks)],
      ["Completed", String(schedule.stats.completedTasks)],
      ["Overall progress", `${schedule.stats.overallProgress}%`],
      ["Critical tasks", String(schedule.stats.criticalTaskCount)],
      ["Delayed tasks", String(schedule.stats.delayedTasks)],
      ["Scheduling conflicts", String(schedule.conflicts.length)],
    ],
    columnStyles: { 0: { cellWidth: 46, fontStyle: "bold", textColor: MUTED } },
  });
}

function taskTablePage(
  doc: jsPDF,
  project: Project,
  schedule: ScheduleResult,
  margin: number,
) {
  const y = sectionHeader(doc, "4  Task Schedule", margin, 24);
  const byId = new Map(schedule.tasks.map((t) => [t.id, t]));
  const rows = project.tasks.map((t) => {
    const s = (byId.get(t.id) as ScheduledTask | undefined) ?? null;
    const indent = "  ".repeat(s?.depth ?? 0);
    return [
      `${indent}${t.isMilestone ? "◆ " : ""}${t.name}`,
      formatShort(t.startDate),
      formatShort(t.endDate),
      t.isMilestone ? "—" : String(t.duration),
      `${t.progress}%`,
      STATUS_META[t.status].label,
      t.assignee || "—",
    ];
  });
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: "striped",
    styles: { fontSize: 8.5, cellPadding: 2 },
    head: [["Task", "Start", "End", "Days", "Prog.", "Status", "Assignee"]],
    body: rows,
    headStyles: { fillColor: NASA_BLUE, textColor: 255 },
    columnStyles: {
      0: { cellWidth: "auto" },
      3: { halign: "right" },
      4: { halign: "right" },
    },
    didParseCell: (data) => {
      const task = schedule.tasks[data.row.index];
      if (data.section === "body" && task?.critical)
        data.cell.styles.textColor = [200, 30, 45];
    },
  });
}

// ── helpers ──────────────────────────────────────────────────────────────────

function sectionHeader(
  doc: jsPDF,
  title: string,
  margin: number,
  y: number,
): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...NASA_BLUE);
  doc.text(title, margin, y);
  doc.setDrawColor(...NASA_BLUE);
  doc.setLineWidth(0.4);
  doc.line(margin, y + 2, doc.internal.pageSize.getWidth() - margin, y + 2);
  return y + 8;
}

function lastY(doc: jsPDF, fallback: number): number {
  const w = doc as jsPDF & { lastAutoTable?: { finalY?: number } };
  return w.lastAutoTable?.finalY ?? fallback;
}

function addImageSafe(
  doc: jsPDF,
  data: string,
  x: number,
  y: number,
  w: number,
  h: number,
  align: "left" | "right" = "left",
) {
  try {
    const props = doc.getImageProperties(data);
    const ratio = props.width / props.height;
    let dw = w;
    let dh = w / ratio;
    if (dh > h) {
      dh = h;
      dw = h * ratio;
    }
    const dx = align === "right" ? x + (w - dw) : x;
    doc.addImage(data, "PNG", dx, y, dw, dh, undefined, "FAST");
  } catch {
    // ignore malformed logo
  }
}

/** Page numbers on every page after the title page (NO author branding). */
function paginate(doc: jsPDF, margin: number) {
  const pages = doc.getNumberOfPages();
  for (let i = 2; i <= pages; i++) {
    doc.setPage(i);
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...MUTED);
    doc.text(`Page ${i} of ${pages}`, pageW - margin, pageH - 8, {
      align: "right",
    });
  }
}
