import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { ReportData } from "./report-types";
import { getMaterial } from "../lib/materials";

/**
 * Builds a professional multi-section engineering PDF (jsPDF + autoTable):
 * cover (with viewport image), geometry & mass properties, material (datasheet
 * + as-printed), orientation, structural simulation (support-polygon stability
 * + linear-elastic FEA, with the heat-map image), 3D-printing estimate, and
 * engineering conclusions. Runs fully client-side and triggers a download.
 * Every page is footed "A product by Asrar ul Haq."
 */

const BRAND = [79, 70, 229] as const; // indigo, matches --color-primary
const INK = [23, 23, 30] as const;
const MUTED = [110, 110, 130] as const;

export async function generateReport(data: ReportData): Promise<void> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 16;

  coverPage(doc, data, pageW, pageH, margin);

  doc.addPage();
  let y = sectionHeader(doc, "Geometry & Mass Properties", margin);
  y = geometryTables(doc, data, margin, y);

  y = ensureSpace(doc, y, 70, margin);
  y = sectionHeader(doc, "Material", margin, y + 6);
  y = materialTable(doc, data, margin, y);

  doc.addPage();
  y = sectionHeader(doc, "Structural Simulation", margin);
  y = simulationSection(doc, data, margin, y, pageW);

  doc.addPage();
  y = sectionHeader(doc, "3D-Printing Estimate", margin);
  y = printingTables(doc, data, margin, y);

  y = ensureSpace(doc, y, 70, margin);
  y = sectionHeader(
    doc,
    "Engineering Conclusions & Recommendations",
    margin,
    y + 6,
  );
  recommendations(doc, data, margin, y, pageW);

  addFooters(doc, pageW, pageH, margin);

  doc.save(`${sanitize(data.modelName)}-am-report.pdf`);
}

// ── Cover ────────────────────────────────────────────────────────────────

function coverPage(
  doc: jsPDF,
  data: ReportData,
  pageW: number,
  pageH: number,
  margin: number,
) {
  doc.setFillColor(...BRAND);
  doc.rect(0, 0, pageW, 6, "F");

  doc.setTextColor(...INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.text("Additive Manufacturing Analyzer", margin, 40);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(13);
  doc.setTextColor(...MUTED);
  doc.text("3D-Printing Engineering Analysis Report", margin, 50);

  // Preview image (fit into a framed box).
  const boxY = 62;
  const boxW = pageW - margin * 2;
  const boxH = 110;
  framedImage(doc, data.previewImage, margin, boxY, boxW, boxH);

  const verdict = data.stability
    ? data.stability.willTip
      ? "Unstable under load"
      : "Stable under load"
    : "—";
  const sf = data.fea
    ? data.fea.safetyFactor >= 999
      ? "∞"
      : data.fea.safetyFactor.toFixed(2)
    : "—";

  const infoY = boxY + boxH + 16;
  doc.setTextColor(...INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  const labels = [
    "Model",
    "Material",
    "Generated",
    "Stability",
    "FEA safety factor",
  ];
  const values = [
    data.modelName,
    data.material.name,
    new Date().toLocaleString(),
    verdict,
    sf,
  ];
  labels.forEach((l, i) => {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...INK);
    doc.text(l, margin, infoY + i * 7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...MUTED);
    doc.text(String(values[i]), margin + 42, infoY + i * 7);
  });

  doc.setDrawColor(...BRAND);
  doc.setLineWidth(0.5);
  doc.line(margin, pageH - 24, pageW - margin, pageH - 24);
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  doc.text("Generated by tools.asrarul.com", margin, pageH - 16);
  doc.text("A product by Asrar ul Haq.", margin, pageH - 11);
}

function framedImage(
  doc: jsPDF,
  image: string | null,
  x: number,
  y: number,
  w: number,
  h: number,
) {
  doc.setDrawColor(220);
  doc.roundedRect(x, y, w, h, 3, 3, "S");
  if (image) {
    try {
      doc.addImage(image, "PNG", x + 4, y + 4, w - 8, h - 8, undefined, "FAST");
      return;
    } catch {
      // fall through to placeholder
    }
  }
  doc.setFontSize(11);
  doc.setTextColor(...MUTED);
  doc.text("No preview captured", x + w / 2, y + h / 2, { align: "center" });
}

// ── Section helpers ─────────────────────────────────────────────────────────

function sectionHeader(
  doc: jsPDF,
  title: string,
  margin: number,
  y = 22,
): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...BRAND);
  doc.text(title, margin, y);
  doc.setDrawColor(...BRAND);
  doc.setLineWidth(0.4);
  doc.line(margin, y + 2, margin + 40, y + 2);
  return y + 8;
}

function table(
  doc: jsPDF,
  startY: number,
  margin: number,
  rows: Array<[string, string]>,
  head?: [string, string],
): number {
  autoTable(doc, {
    startY,
    margin: { left: margin, right: margin },
    head: head ? [head] : undefined,
    body: rows,
    theme: "striped",
    styles: { fontSize: 9.5, cellPadding: 2 },
    headStyles: { fillColor: [...BRAND], textColor: 255 },
    columnStyles: { 0: { cellWidth: 72, textColor: [...MUTED] } },
  });
  return lastFinalY(doc, startY + 10);
}

function lastFinalY(doc: jsPDF, fallback: number): number {
  const withTable = doc as jsPDF & { lastAutoTable?: { finalY?: number } };
  return withTable.lastAutoTable?.finalY ?? fallback;
}

function ensureSpace(
  doc: jsPDF,
  y: number,
  needed: number,
  margin: number,
): number {
  const pageH = doc.internal.pageSize.getHeight();
  if (y + needed > pageH - 24) {
    doc.addPage();
    return margin + 6;
  }
  return y;
}

// ── Content sections ─────────────────────────────────────────────────────

function geometryTables(
  doc: jsPDF,
  { geometry, orientation }: ReportData,
  margin: number,
  y: number,
): number {
  const { boundingBox: bb, diagnostics: d, quality: q } = geometry;
  const f = (n: number, u = "mm") => `${n.toFixed(2)} ${u}`;
  return table(
    doc,
    y,
    margin,
    [
      [
        "Orientation (X, Y, Z)",
        `${orientation.rx.toFixed(0)}°, ${orientation.ry.toFixed(0)}°, ${orientation.rz.toFixed(0)}°`,
      ],
      [
        "Footprint (X × Y)",
        `${bb.size[0].toFixed(1)} × ${bb.size[1].toFixed(1)} mm`,
      ],
      ["Height (Z)", f(bb.size[2])],
      ["Volume", f(geometry.volume, "mm³")],
      ["Surface area", f(geometry.surfaceArea, "mm²")],
      [
        "Center of mass",
        geometry.centerOfMass.map((c) => c.toFixed(1)).join(", "),
      ],
      ["Triangles", q.triangleCount.toLocaleString()],
      ["Unique vertices", q.uniqueVertexCount.toLocaleString()],
      ["Watertight", d.watertight ? "Yes" : "No"],
      ["Non-manifold edges", String(d.nonManifoldEdges)],
      ["Holes", String(d.holes)],
      ["Overhang area", `${(d.overhangArea * 100).toFixed(0)}%`],
      ["Printability score", `${geometry.printabilityScore}/100`],
      ["Mesh quality score", `${q.score}/100`],
      ["Complexity score", `${geometry.complexityScore}/100`],
    ],
    ["Geometry", "Value"],
  );
}

function materialTable(
  doc: jsPDF,
  { material, effective }: ReportData,
  margin: number,
  y: number,
): number {
  y = table(
    doc,
    y,
    margin,
    [
      ["Material", material.name],
      ["Density (solid)", `${material.density} g/cm³`],
      ["Young's modulus", `${material.youngsModulus} MPa`],
      ["Yield strength", `${material.yieldStrength} MPa`],
      ["Ultimate strength", `${material.ultimateStrength} MPa`],
      ["Poisson ratio", String(material.poissonRatio)],
      ["Thermal expansion", `${material.thermalExpansion} µm/m·°C`],
      ["Cost", `$${material.costPerKg}/kg`],
    ],
    ["Datasheet Property", "Value"],
  );

  if (effective) {
    y = table(
      doc,
      y + 4,
      margin,
      [
        [
          "Solid fraction (walls + infill)",
          `${(effective.solidFraction * 100).toFixed(0)}%`,
        ],
        [
          "Effective modulus (in-plane)",
          `${effective.modulusXY.toFixed(0)} MPa`,
        ],
        ["Effective modulus (build Z)", `${effective.modulusZ.toFixed(0)} MPa`],
        [
          "Effective strength (in-plane)",
          `${effective.strengthXY.toFixed(1)} MPa`,
        ],
        [
          "Effective strength (interlayer Z)",
          `${effective.strengthZ.toFixed(1)} MPa`,
        ],
        [
          "Layer anisotropy (Z/XY)",
          `${(effective.anisotropy * 100).toFixed(0)}%`,
        ],
        ["Effective density", `${effective.density.toFixed(2)} g/cm³`],
      ],
      ["As-Printed Property", "Value"],
    );
  }
  return y;
}

function simulationSection(
  doc: jsPDF,
  data: ReportData,
  margin: number,
  y: number,
  pageW: number,
): number {
  const { stability, fea, forces, constraint } = data;

  // Constraint + force summary.
  y = table(
    doc,
    y,
    margin,
    [
      ["Constraint", constraintLabel(constraint.mode)],
      ["Applied forces", String(forces.length)],
    ],
    ["Load Case", "Value"],
  );

  // Per-force list.
  if (forces.length) {
    autoTable(doc, {
      startY: y + 4,
      margin: { left: margin, right: margin },
      head: [["Force", "Magnitude", "Direction", "Location (mm)"]],
      body: forces.map((f) => [
        f.name,
        `${f.magnitude} N`,
        `[${f.direction.map((d) => d.toFixed(1)).join(", ")}]`,
        `[${f.point.map((p) => p.toFixed(0)).join(", ")}]`,
      ]),
      theme: "striped",
      styles: { fontSize: 9, cellPadding: 2 },
      headStyles: { fillColor: [...BRAND], textColor: 255 },
    });
    y = lastFinalY(doc, y + 10);
  }

  // Stability.
  if (stability) {
    y = ensureSpace(doc, y, 60, margin);
    y = table(
      doc,
      y + 4,
      margin,
      [
        ["Mass", `${stability.massGrams.toFixed(1)} g`],
        [
          "Center of gravity",
          stability.centerOfGravity.map((c) => c.toFixed(1)).join(", "),
        ],
        [
          "CoG over support polygon",
          stability.cogInsidePolygon ? "Inside" : "Outside",
        ],
        ["Stability margin", `${stability.stabilityMargin.toFixed(1)} mm`],
        ["Overturning moment", `${stability.overturningTorque.toFixed(2)} N·m`],
        ["Restoring moment", `${stability.restoringTorque.toFixed(2)} N·m`],
        [
          "Factor of safety (tipping)",
          stability.tippingThreshold >= 999
            ? "∞"
            : stability.tippingThreshold.toFixed(2),
        ],
        ["Verdict", stability.willTip ? "Tips over" : "Stable"],
      ],
      ["Stability", "Result"],
    );
  }

  // FEA numbers + image.
  if (fea) {
    y = ensureSpace(doc, y, 70, margin);
    y = table(
      doc,
      y + 4,
      margin,
      [
        ["Method", "Linear-elastic voxel-hex FEM"],
        [
          "Mesh resolution",
          `${fea.resolution}³ voxels (${fea.elementCount.toLocaleString()} elements)`,
        ],
        ["Solver converged", fea.converged ? "Yes" : "Max iterations"],
        ["Max von Mises stress", `${fea.maxStress.toFixed(2)} MPa`],
        ["Max displacement", `${fea.maxDisplacement.toFixed(3)} mm`],
        ["Estimated peak strain", fea.estimatedStrain.toExponential(2)],
        [
          "Safety factor",
          fea.safetyFactor >= 999 ? "∞" : fea.safetyFactor.toFixed(2),
        ],
      ],
      ["FEA", "Result"],
    );

    if (data.feaImage) {
      y = ensureSpace(doc, y, 96, margin);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(...INK);
      doc.text("Von Mises stress field", margin, y + 6);
      framedImage(doc, data.feaImage, margin, y + 9, pageW - margin * 2, 82);
      y += 94;
    }
  } else {
    y = table(doc, y + 4, margin, [
      ["Note", "No load case defined — add forces to run FEA."],
    ]);
  }
  return y;
}

function constraintLabel(mode: string): string {
  switch (mode) {
    case "build-plate":
      return "Build plate fixed";
    case "bottom-face":
      return "Bottom face fixed";
    case "selected-face":
      return "Selected face fixed";
    default:
      return "Custom constraints";
  }
}

function printingTables(
  doc: jsPDF,
  { printEstimate: p, printSettings: s, material }: ReportData,
  margin: number,
  y: number,
): number {
  y = table(
    doc,
    y,
    margin,
    [
      ["Material", material.name],
      ["Infill", `${s.infillPercent}% ${s.infillPattern}`],
      ["Layer height", `${s.layerHeight} mm`],
      ["Nozzle", `${s.nozzleDiameter} mm`],
      ["Walls", `${s.wallCount}`],
      ["Top / bottom layers", `${s.topLayers} / ${s.bottomLayers}`],
      ["Print speed", `${s.printSpeed} mm/s`],
      ["Supports", s.supports ? "Yes" : "No"],
      ["Adhesion", s.brimRaft],
    ],
    ["Print Setting", "Value"],
  );

  if (p) {
    y = table(
      doc,
      y + 4,
      margin,
      [
        ["Print time", `${p.printTimeHours.toFixed(1)} h`],
        ["Filament length", `${p.filamentLengthM.toFixed(1)} m`],
        ["Material weight", `${p.materialWeightGrams.toFixed(1)} g`],
        ["Material cost", `$${p.materialCost.toFixed(2)}`],
        ["Electricity cost", `$${p.electricityCost.toFixed(2)}`],
        ["Total cost", `$${p.totalCost.toFixed(2)}`],
        ["CO₂ estimate", `${p.co2Grams.toFixed(0)} g`],
        ["Difficulty", p.difficulty],
        ["Failure risk", `${(p.failureRisk * 100).toFixed(0)}%`],
        ["Warp risk", `${(p.warpRisk * 100).toFixed(0)}%`],
      ],
      ["Estimate", "Value"],
    );
  }
  return y;
}

function recommendations(
  doc: jsPDF,
  { recommendation, stability, fea }: ReportData,
  margin: number,
  y: number,
  pageW: number,
) {
  const lines: string[] = [];
  if (fea) {
    if (fea.safetyFactor < 1) {
      lines.push(
        `The current load case yields (safety factor ${fea.safetyFactor.toFixed(2)} < 1). Reduce the load, reinforce the part, increase infill/walls, or select a stronger material.`,
      );
    } else if (fea.safetyFactor < 2) {
      lines.push(
        `Marginal safety factor (${fea.safetyFactor.toFixed(2)}). Consider more infill or walls for a robust design margin.`,
      );
    } else {
      lines.push(
        `Healthy structural margin (safety factor ${fea.safetyFactor.toFixed(2)}). The design withstands the applied load with room to spare.`,
      );
    }
  }
  if (stability) lines.push(`Stability: ${stability.recommendation}`);
  if (recommendation) {
    lines.push(
      `Suggested material: ${getMaterial(recommendation.bestMaterialId).name}.`,
    );
    lines.push(
      `Suggested infill: ${recommendation.infillPercent}%; layer height ${recommendation.layerHeight} mm.`,
    );
    lines.push(`Orientation: ${recommendation.orientation}`);
    lines.push(`Supports: ${recommendation.supportStrategy}`);
  }

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...INK);
  let cursor = y + 2;
  for (const line of lines) {
    const wrapped = doc.splitTextToSize(`•  ${line}`, pageW - margin * 2);
    doc.text(wrapped, margin, cursor);
    cursor += wrapped.length * 5 + 2;
  }
}

function addFooters(doc: jsPDF, pageW: number, pageH: number, margin: number) {
  const pages = doc.getNumberOfPages();
  for (let i = 2; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(
      "Generated by tools.asrarul.com  ·  A product by Asrar ul Haq.",
      margin,
      pageH - 8,
    );
    doc.text(`Page ${i} / ${pages}`, pageW - margin, pageH - 8, {
      align: "right",
    });
  }
}

function sanitize(name: string): string {
  return name.replace(/\.[^.]+$/, "").replace(/[^a-z0-9-_]+/gi, "-");
}
