import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { ReportData } from "./report-types";
import { getMaterial } from "../lib/materials";

/**
 * Builds a professional multi-section engineering PDF with jsPDF + autoTable:
 * cover (with viewport image), geometry, material, simulation, printing, and
 * final recommendations. Runs fully client-side and triggers a download.
 */

const BRAND = [79, 70, 229] as const; // indigo, matches --color-primary
const INK = [23, 23, 30] as const;
const MUTED = [110, 110, 130] as const;

export async function generateReport(data: ReportData): Promise<void> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 16;

  coverPage(doc, data, pageW, pageH, margin);

  doc.addPage();
  let y = sectionHeader(doc, "Geometry Report", margin);
  y = geometryTables(doc, data, margin, y);

  y = ensureSpace(doc, y, 60, margin);
  y = sectionHeader(doc, "Material Report", margin, y + 6);
  y = materialTable(doc, data, margin, y);

  y = ensureSpace(doc, y, 70, margin);
  y = sectionHeader(doc, "Simulation Report", margin, y + 6);
  y = simulationTables(doc, data, margin, y);

  doc.addPage();
  y = sectionHeader(doc, "Printing Report", margin);
  y = printingTables(doc, data, margin, y);

  y = ensureSpace(doc, y, 60, margin);
  y = sectionHeader(doc, "Final Engineering Recommendations", margin, y + 6);
  recommendations(doc, data, margin, y, pageW);

  addFooters(doc, pageW, pageH, margin);

  doc.save(`${sanitize(data.modelName)}-engineering-report.pdf`);
}

// ── Cover ────────────────────────────────────────────────────────────────

function coverPage(
  doc: jsPDF,
  data: ReportData,
  pageW: number,
  pageH: number,
  margin: number,
) {
  doc.setFillColor(...BRAND);
  doc.rect(0, 0, pageW, 6, "F");

  doc.setTextColor(...INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.text("STL Engineering Analyzer", margin, 40);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(13);
  doc.setTextColor(...MUTED);
  doc.text("Engineering Analysis Report", margin, 50);

  // Preview image (fit into a framed box).
  const boxY = 62;
  const boxW = pageW - margin * 2;
  const boxH = 110;
  doc.setDrawColor(220);
  doc.roundedRect(margin, boxY, boxW, boxH, 3, 3, "S");
  if (data.previewImage) {
    try {
      doc.addImage(
        data.previewImage,
        "PNG",
        margin + 4,
        boxY + 4,
        boxW - 8,
        boxH - 8,
        undefined,
        "FAST",
      );
    } catch {
      // Ignore malformed image data.
    }
  } else {
    doc.setFontSize(11);
    doc.text("No preview captured", pageW / 2, boxY + boxH / 2, {
      align: "center",
    });
  }

  const infoY = boxY + boxH + 16;
  doc.setTextColor(...INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Model", margin, infoY);
  doc.text("Generated", margin, infoY + 8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...MUTED);
  doc.text(data.modelName, margin + 30, infoY);
  doc.text(new Date().toLocaleString(), margin + 30, infoY + 8);

  doc.setDrawColor(...BRAND);
  doc.setLineWidth(0.5);
  doc.line(margin, pageH - 24, pageW - margin, pageH - 24);
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  doc.text("Generated by tools.asrarul.com", margin, pageH - 16);
  doc.text("A product of Asrar ul Haq", margin, pageH - 11);
}

// ── Section helpers ─────────────────────────────────────────────────────────

function sectionHeader(doc: jsPDF, title: string, margin: number, y = 22): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...BRAND);
  doc.text(title, margin, y);
  doc.setDrawColor(...BRAND);
  doc.setLineWidth(0.4);
  doc.line(margin, y + 2, margin + 40, y + 2);
  return y + 8;
}

function table(
  doc: jsPDF,
  startY: number,
  margin: number,
  rows: Array<[string, string]>,
  head?: [string, string],
): number {
  autoTable(doc, {
    startY,
    margin: { left: margin, right: margin },
    head: head ? [head] : undefined,
    body: rows,
    theme: "striped",
    styles: { fontSize: 9.5, cellPadding: 2 },
    headStyles: { fillColor: [...BRAND], textColor: 255 },
    columnStyles: { 0: { cellWidth: 70, textColor: [...MUTED] } },
  });
  return lastFinalY(doc, startY + 10);
}

/**
 * autoTable records the ending Y on `doc.lastAutoTable.finalY` at runtime, but
 * that property isn't in jsPDF's public type. Read it through a narrow cast.
 */
function lastFinalY(doc: jsPDF, fallback: number): number {
  const withTable = doc as jsPDF & {
    lastAutoTable?: { finalY?: number };
  };
  return withTable.lastAutoTable?.finalY ?? fallback;
}

function ensureSpace(
  doc: jsPDF,
  y: number,
  needed: number,
  margin: number,
): number {
  const pageH = doc.internal.pageSize.getHeight();
  if (y + needed > pageH - 24) {
    doc.addPage();
    return margin + 6;
  }
  return y;
}

// ── Content sections ─────────────────────────────────────────────────────

function geometryTables(
  doc: jsPDF,
  { geometry }: ReportData,
  margin: number,
  y: number,
): number {
  const { boundingBox: bb, diagnostics: d, quality: q } = geometry;
  const f = (n: number, u = "mm") => `${n.toFixed(2)} ${u}`;
  y = table(
    doc,
    y,
    margin,
    [
      ["Dimensions (X × Y × Z)", `${bb.size.map((s) => s.toFixed(1)).join(" × ")} mm`],
      ["Volume", f(geometry.volume, "mm³")],
      ["Surface area", f(geometry.surfaceArea, "mm²")],
      ["Center of mass", geometry.centerOfMass.map((c) => c.toFixed(1)).join(", ")],
      ["Triangles", q.triangleCount.toLocaleString()],
      ["Unique vertices", q.uniqueVertexCount.toLocaleString()],
      ["Watertight", d.watertight ? "Yes" : "No"],
      ["Non-manifold edges", String(d.nonManifoldEdges)],
      ["Holes", String(d.holes)],
      ["Min wall thickness", f(d.minWallThickness)],
      ["Printability score", `${geometry.printabilityScore}/100`],
      ["Mesh quality score", `${q.score}/100`],
      ["Complexity score", `${geometry.complexityScore}/100`],
    ],
    ["Geometry", "Value"],
  );
  return y;
}

function materialTable(
  doc: jsPDF,
  { material }: ReportData,
  margin: number,
  y: number,
): number {
  return table(
    doc,
    y,
    margin,
    [
      ["Material", material.name],
      ["Density", `${material.density} g/cm³`],
      ["Young's modulus", `${material.youngsModulus} MPa`],
      ["Yield strength", `${material.yieldStrength} MPa`],
      ["Ultimate strength", `${material.ultimateStrength} MPa`],
      ["Poisson ratio", String(material.poissonRatio)],
      ["Thermal expansion", `${material.thermalExpansion} µm/m·°C`],
      ["Cost", `$${material.costPerKg}/kg`],
    ],
    ["Property", "Value"],
  );
}

function simulationTables(
  doc: jsPDF,
  { stability, fea, forces }: ReportData,
  margin: number,
  y: number,
): number {
  const rows: Array<[string, string]> = [];
  rows.push(["Applied forces", String(forces.length)]);
  if (stability) {
    rows.push(["Estimated mass", `${stability.massGrams.toFixed(1)} g`]);
    rows.push(["Tipping factor", stability.tippingThreshold.toFixed(2)]);
    rows.push(["Overturning torque", `${stability.overturningTorque.toFixed(2)} N·m`]);
    rows.push(["Restoring torque", `${stability.restoringTorque.toFixed(2)} N·m`]);
    rows.push(["Verdict", stability.willTip ? "Tips over" : "Stable"]);
  }
  if (fea) {
    rows.push(["Max von Mises stress", `${fea.maxStress.toFixed(2)} MPa (approx.)`]);
    rows.push(["Max displacement", `${fea.maxDisplacement.toFixed(3)} mm`]);
    rows.push(["Estimated strain", fea.estimatedStrain.toExponential(2)]);
    rows.push([
      "Safety factor",
      fea.safetyFactor >= 999 ? "∞" : fea.safetyFactor.toFixed(2),
    ]);
  }
  if (rows.length === 1) {
    rows.push(["Note", "No load case defined — add forces/supports for FEA."]);
  }
  return table(doc, y, margin, rows, ["Simulation", "Result"]);
}

function printingTables(
  doc: jsPDF,
  { printEstimate: p, printSettings: s, material }: ReportData,
  margin: number,
  y: number,
): number {
  y = table(
    doc,
    y,
    margin,
    [
      ["Material", material.name],
      ["Infill", `${s.infillPercent}% ${s.infillPattern}`],
      ["Layer height", `${s.layerHeight} mm`],
      ["Nozzle", `${s.nozzleDiameter} mm`],
      ["Walls / top-bottom", `${s.wallCount} / ${s.topBottomLayers}`],
      ["Print speed", `${s.printSpeed} mm/s`],
      ["Supports", s.supports ? "Yes" : "No"],
      ["Adhesion", s.brimRaft],
    ],
    ["Print Setting", "Value"],
  );

  if (p) {
    y = table(
      doc,
      y + 4,
      margin,
      [
        ["Print time", `${p.printTimeHours.toFixed(1)} h`],
        ["Filament length", `${p.filamentLengthM.toFixed(1)} m`],
        ["Material weight", `${p.materialWeightGrams.toFixed(1)} g`],
        ["Material cost", `$${p.materialCost.toFixed(2)}`],
        ["Electricity cost", `$${p.electricityCost.toFixed(2)}`],
        ["Total cost", `$${p.totalCost.toFixed(2)}`],
        ["CO₂ estimate", `${p.co2Grams.toFixed(0)} g`],
        ["Difficulty", p.difficulty],
        ["Failure risk", `${(p.failureRisk * 100).toFixed(0)}%`],
        ["Warp risk", `${(p.warpRisk * 100).toFixed(0)}%`],
      ],
      ["Estimate", "Value"],
    );
  }
  return y;
}

function recommendations(
  doc: jsPDF,
  { recommendation, stability }: ReportData,
  margin: number,
  y: number,
  pageW: number,
) {
  const lines: string[] = [];
  if (recommendation) {
    lines.push(`Best material: ${getMaterial(recommendation.bestMaterialId).name}`);
    lines.push(`Recommended infill: ${recommendation.infillPercent}%`);
    lines.push(`Recommended layer height: ${recommendation.layerHeight} mm`);
    lines.push(`Orientation: ${recommendation.orientation}`);
    lines.push(`Supports: ${recommendation.supportStrategy}`);
  }
  if (stability) lines.push(`Stability: ${stability.recommendation}`);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...INK);
  let cursor = y + 2;
  for (const line of lines) {
    const wrapped = doc.splitTextToSize(`•  ${line}`, pageW - margin * 2);
    doc.text(wrapped, margin, cursor);
    cursor += wrapped.length * 5 + 2;
  }
}

function addFooters(doc: jsPDF, pageW: number, pageH: number, margin: number) {
  const pages = doc.getNumberOfPages();
  for (let i = 2; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text("Generated by tools.asrarul.com  ·  A product of Asrar ul Haq", margin, pageH - 8);
    doc.text(`Page ${i} / ${pages}`, pageW - margin, pageH - 8, { align: "right" });
  }
}

function sanitize(name: string): string {
  return name.replace(/\.[^.]+$/, "").replace(/[^a-z0-9-_]+/gi, "-");
}
